### ISSUE TITLE
Running Impedance 4 Wire Sample in Release doesn't work

### ISSUE THREAD

**Issue by dioptre** [dioptre/ADuCM350#6]
Issue at https://github.com/dioptre/ADuCM350/blob/024cc7293d159d8be11b8ce0e9fe4a1a93a2f361/src/Impedance4WireTest.c#L480

```
magnitude = (magnitude << 5) / (q63_t)magnitude_2;
```
The division is bugging out by the looks of it.

**Works when debugger/semihosting is attached.**

I replaced the union datatype with a raw q63_t to simplify things, and here are my results so far:
```
/* Calculates magnitude.                                */
/* performs the calculation:                            */
/*      magnitude = magnitude_1 / magnitude_2 * res     */
/* Output in custom fixed-point format (28.4)           */
q63_t calculate_magnitude(q31_t magnitude_1, q31_t magnitude_2, uint32_t res)
{
    q63_t magnitude;
    magnitude = (q63_t)0;

    if ((q63_t)0 != magnitude_2)
    {
        magnitude = (q63_t)magnitude_1 * (q63_t)res; //0xb70744cc0 = 16a09 * 816c; should be b70744cc

        magnitude = magnitude << 5; //0xe0e8998016, should be 0x16E0E89980


        //magnitude = 4 / 2; //OK
        //magnitude = magnitude_1 / magnitude_2; //OK
        //magnitude = magnitude / m2; //FAILS
        //magnitude = magnitude / (q63_t)magnitude_2; //div by 5a827 FAILS, should be 40B5D.DAE899E97
        //magnitude = magnitude / 370727; //FAILS
        //magnitude = magnitude / 1; //OK
        //magnitude = magnitude / 227; //FAILS
        //magnitude = -521627264 / 227; //OK
        //magnitude = -521627264 / 370727; //OK
        char str[300];
        uint32_t* m32ptr = (uint32_t*)&magnitude;
        sprintf(str, "m1: %x m2: %x res: %x\n", magnitude_1, magnitude_2, res);
        PRINT(str);
        sprintf(str, "%x%x\n", *m32ptr, *(m32ptr+1));
        PRINT(str);
		char* ptr = (char*)&magnitude;
		for (int i =0; i<9; i++, ptr++)
			str[i] = *ptr;
		PRINT("...");
		PRINT(str);
		PRINT("...");
		sprintf(str, "%x%x", magnitude);
		PRINT(str);
        BlinkSetup();
		Blink();

		return magnitude;
```

**Comment by dioptre** [comment]
Ok this works wtf
```
    	magnitude = (q63_t)(((magnitude_1 * res) << 5 ) / magnitude_2); //WORKS WTF

        /* Rounding */
        magnitude = (magnitude + 1) >> 1;
```
Can someone please double check this? Looks like arm didn't implement the / operator for q63_t srsly?

**Comment by JeanRintoul** [comment]
What is the error msg you are getting? Is it some sort of overflow error? What are the values of 
magnitude_1 and magnitude_2 when this happens, i.e. maybe the custom fixed point data type q63_t isn't defined properly yet, or it overflow in this case? q63_t says its a custom 64-bit fractional data type in 1.63 format( https://en.wikipedia.org/wiki/Q_(number_format), not particularly familiar with this data type before)...

**Comment by dioptre** [comment]
Funny thing is I tried with const variables and it works. The data is as above (in hex). I'm going to compare the hack I made to the original and here's hoping it works. Otherwise I'll look at overloading the operator I guess?

**Comment by dioptre** [comment]
Argh turns out the chip doesnt do division, and its been off loading it to my semihost...

**Comment by dioptre** [comment]
My magnitude_2 is > 32bit, so will need to implement something else, or check if that value is correct.
